server:
  port:8080

spring:
  datasource:
    url : jdbc:postgresql://localhost:5432/postgres
    username : postgres
    password : pwc


    jpa:
      hibernate:
        ddl-auto: update
        show-sql : true

